package.json, src/lib/app/types/layout.ts, src/lib/components/identity/identity-details.svelte, src/lib/components/identity/identity-list.svelte, src/lib/components/list-manager.svelte, src/lib/components/streams/channel-messages.svelte, src/lib/components/streams/channel-subscriptions.svelte
chore: merge `iota-community` `dev` branch to `dev`
- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix
=> chore: merge `iota-community` `dev` branch to `dev`

src/lib/components/identity/identity-details.svelte, src/lib/components/identity/identity-manager.svelte
Identities without default templates did not have an icon. This PR fixes that and adds a default icon.
=> Feat: Add default identity icon type

README.md, package-lock.json, package.json, src/lib/app/base.ts, src/lib/app/streams.ts, src/lib/components/identity/identity-details.svelte, src/lib/components/identity/identity-manager.svelte, src/lib/components/streams/streams-manager.svelte, src/lib/components/streams/write-message-modal.svelte, src/routes/__layout.svelte
- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix
=> chore: merge `dev` into `main`

package-lock.json, package.json, src/lib/app/constants/base.ts, src/lib/app/constants/identity.ts, src/lib/app/identity.ts, src/lib/components/identity/identity-manager.svelte, src/lib/components/list-manager.svelte, src/lib/components/streams/channel-info.svelte, src/lib/components/streams/streams-manager.svelte, src/lib/components/table.svelte
Add names and description for channels. Make loading channels and identities dynamic.
- remove placeholder for names, descriptions of channels
- add dynamic loading for list pages
- load more button is showed on last page entry 
Started and clicked through pages and loaded new entries
=> Minor changes

package.json, src/lib/app/streams.ts, src/lib/components/streams/channel-details.svelte, src/lib/components/streams/streams-manager.svelte
- fix polling if it is a subscriber
- continue polling if an error occurs
- Bug fix (a non-breaking change which fixes an issue)
=> fix subscription messages problem

package-lock.json, package.json, src/lib/app/streams.ts, src/lib/components/streams/channel-details.svelte, src/lib/components/streams/create-channel-modal.svelte, src/lib/components/streams/history-form.svelte, src/lib/components/streams/history.svelte
This PR aims to fix the CI build
-   Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   Documentation Fix
-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have checked that new and existing unit tests pass locally with my changes
-   [ ] I have updated the CHANGELOG.md, if my changes are significant enough
=> Fix: imports

src/lib/app/identity.ts, src/lib/app/streams.ts
Added one extra notification if channel or identity already exists.
Manually by trying to register one existing identity and channel again.
=> provided feedback if channel and identitiy already exist

package-lock.json, package.json, src/lib/components/streams/streams-manager.svelte
fix pagination for streams manager
=> fix pagination for streams manager

package-lock.json, package.json, src/lib/components/identity/create-credential-modal.svelte, src/lib/components/identity/create-identity-modal.svelte, src/lib/components/login-register/login-register-manager.svelte, src/lib/components/login-register/register.svelte
=> 49 fix register dialog

package-lock.json, package.json, src/lib/app/constants/streams.ts, src/lib/app/streams.ts, src/lib/app/types/streams.ts, src/lib/components/identity/identity-manager.svelte, src/lib/components/list-manager.svelte, src/lib/components/streams/channel-info.svelte, src/lib/components/streams/streams-manager.svelte
In the channels overview the user can now search for subscribed and requested channels.
Manually. For that run the docker-compose file in integration-services from branch `25-query-subscribed-channels`.
Stop the is-dashboard container and run the dashboard from branch `38-search-for-subscribed-channels`.
Use a CORS plugin in the browser.
=> checkboxes added for filtering of subscribed and requested channels

CHANGELOG.md, package-lock.json, package.json, src/lib/app/streams.ts
Updated to newest version of is-client to make ui-component web-compatible again
Manual testing, build and dev scripts
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have checked that new and existing unit tests pass locally with my changes
=> Updated is-client and imports

CHANGELOG.md, package.json, src/lib/scss/colors.scss
Fixed .scss imports
Manuel testing
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have checked that new and existing unit tests pass locally with my changes
=> fixed scss imports

CHANGELOG.md, package.json, src/lib/index.ts, src/lib/scss/colors.scss
Fixed css imports
Deployed to npm and installed in is-dashboard
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have checked that new and existing unit tests pass locally with my changes
=> 81 update project dependencies

CHANGELOG.md, package-lock.json, package.json, src/lib/app/identity.ts, src/lib/app/types/identity.ts, src/lib/components/identity/identity-details.svelte, src/lib/components/identity/identity-manager.svelte, src/lib/components/login-register/login.svelte, src/routes/identity-manager/[id].svelte
Updated is-client version
-   Breaking change (fix or feature that would cause existing functionality to not work as expected)
Manually : login, create identity, vc, revoke vc, 
=> 85 is UI components update

.github/workflows/publish-on-npmjs.yaml
-   Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   Documentation Fix
-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have checked that new and existing unit tests pass locally with my changes
-   [ ] I have updated the CHANGELOG.md, if my changes are significant enough
=> rearrranged run tasks

.github/workflows/publish-on-npmjs.yaml
-   Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   Documentation Fix
-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have checked that new and existing unit tests pass locally with my changes
-   [ ] I have updated the CHANGELOG.md, if my changes are significant enough
=> 89 set latest npm version

.github/workflows/publish-on-npmjs.yaml, CHANGELOG.md, package-lock.json, package.json, src/lib/app/base.ts
=> upgrade of version and worklfow adjustments

src/lib/components/streams/create-channel-modal.svelte, src/lib/components/streams/history-form.svelte
Added an if statement in history component for adding preshared key when a private channel is chosen.
=> added if statement for private channels

CHANGELOG.md, package-lock.json, package.json, src/lib/components/identity/identity-details.svelte, src/lib/components/streams/subscription.svelte, src/routes/identity-manager/[id].svelte, src/routes/streams-manager/[channelAddress].svelte
Add links to identity ids for identity details and channel details
=> 84 add link to identities

package-lock.json, package.json, src/lib/components/streams/channel-messages.svelte
- add source to message data
- remove streams link
=> add source to message data, remove streams link
